'use strict';
const {tempoDe, eventos, ESTACOES}=require('./calendario');
const {humano}=require('./seres');
const VERSAO=4;
function novo(){const ciclo=24,tempo=tempoDe(ciclo);return{versao:VERSAO,mundo:{tempo,clima:eventos(tempo).chuva,ecossistema:{agua:{nascente:42,limite:60,chuvaAcumulada:0},peixes:{rio:{populacao:24,capacidade:40,idadeMedia:12}},arvores:{a:{local:'bosque',frutos:5,capacidadeFrutos:12,saude:90,idade:18},b:{local:'bosque',frutos:3,capacidadeFrutos:10,saude:75,idade:9},c:{local:'floresta',frutos:0,capacidadeFrutos:0,saude:95,idade:24}},madeira:{floresta:18},animais:{aves:{local:'bosque',populacao:8,capacidade:16,idadeMedia:20},roedores:{local:'floresta',populacao:6,capacidade:14,idadeMedia:10}}}},seres:{icaro:humano()},descobertas:[],memorias:[]}}
function validar(e){const bad=m=>{throw Error('Estado V2 inválido: '+m)};if(!e||e.versao!==VERSAO)bad('versão incompatível');const t=e.mundo?.tempo;if(!t||!Number.isInteger(t.ciclo)||t.ciclo<0)bad('calendário/ciclo inválido');const c=tempoDe(t.ciclo);if(t.dia!==c.dia||t.periodo!==c.periodo||t.periodoIndex!==c.periodoIndex||t.estacao!==c.estacao||t.diaDaEstacao!==c.diaDaEstacao||t.ano!==c.ano)bad('calendário divergente do ciclo');const x=e.mundo.ecossistema;if(!x?.agua||!x?.peixes?.rio||!x.arvores||!x.madeira||!x.animais)bad('ecossistema incompleto');const vals=[x.agua.nascente,x.agua.limite,x.agua.chuvaAcumulada,x.peixes.rio.populacao,x.peixes.rio.capacidade,...Object.values(x.arvores).flatMap(a=>[a.frutos,a.capacidadeFrutos,a.saude,a.idade]),...Object.values(x.madeira),...Object.values(x.animais).flatMap(a=>[a.populacao,a.capacidade,a.idadeMedia])];if(vals.some(v=>!Number.isFinite(v)||v<0))bad('estoque/atributo ecológico inválido');if(x.agua.nascente>x.agua.limite||x.peixes.rio.populacao>x.peixes.rio.capacidade||Object.values(x.arvores).some(a=>a.frutos>a.capacidadeFrutos)||Object.values(x.animais).some(a=>a.populacao>a.capacidade))bad('estoque acima da capacidade');if(!e.seres||!Object.keys(e.seres).length)bad('nenhum ser definido');for(const[id,s]of Object.entries(e.seres)){if(s.id!==id||!s.necessidades||!s.inventario||!s.capacidades||!['vivo','critico','morto'].includes(s.status))bad('entidade '+id+' incompleta');for(const[k,v]of Object.entries({...s.necessidades,...s.inventario,...s.capacidades}))if(!Number.isFinite(v)||v<0)bad('valor inválido em '+id+'.'+k)}if(!Array.isArray(e.descobertas)||!Array.isArray(e.memorias))bad('memória/descoberta inválida');return e}
function migrar(l){if(!l)return novo();if(l.versao===VERSAO)return validar(l);if((l.versao===2||l.versao===3)&&l.mundo?.ecossistema&&l.seres){const e=JSON.parse(JSON.stringify(l)),t=e.mundo.tempo,ciclo=Number.isInteger(t?.ciclo)?t.ciclo:t?.ciclos;if(!Number.isInteger(ciclo)||ciclo<0)throw Error('Migração V2 cancelada: calendário sem contador confiável; estado original preservado.');t.ciclo=ciclo;delete t.ciclos;Object.assign(t,tempoDe(ciclo));e.mundo.clima=e.mundo.clima||eventos(t).chuva;e.descobertas=Array.isArray(e.descobertas)?e.descobertas:[];e.memorias=Array.isArray(e.memorias)?e.memorias:[];delete e.historico;e.versao=VERSAO;delete e.ultimoCiclo;return validar(e)}if(l.recursos||l.agua!==undefined||l.comida!==undefined||l.dia!==undefined){const e=novo(),r=l.recursos||{};e.seres.icaro.inventario={agua:Number(r.agua??l.agua??8),alimento:Number(r.comida??l.comida??7),madeira:Number(r.madeira??0)};e.seres.icaro.abrigo=Number(l.abrigo??1);e.descobertas=[...(l.descobertas||l.informacoes||[])];e.memorias=e.descobertas.map((texto,i)=>({tipo:'legado',texto,origem:'migração',indice:i}));e.mundo.tempo=tempoDe(Math.max(0,(Number(l.dia||1)-1)*4));e.mundo.clima=eventos(e.mundo.tempo).chuva;return validar(e)}throw Error('Estado não reconhecido; migração cancelada sem sobrescrever os dados.')}
function avancar(m){m.tempo=tempoDe(m.tempo.ciclo+1);m.clima=eventos(m.tempo).chuva;return eventos(m.tempo)}
function regenerar(m,ev){const x=m.ecossistema,q=ev.chuva==='chuva_forte'?3:ev.chuva==='chuva'?1.5:ev.chuva==='chuva_fraca'?.5:0;x.agua.chuvaAcumulada+=q;x.agua.nascente=Math.min(x.agua.limite,x.agua.nascente+(q*.35+(x.agua.nascente>0?.08:0)));for(const a of Object.values(x.arvores)){if(a.saude<=0)continue;if(ev.frutificacao&&ev.regeneracaoVegetal&&a.capacidadeFrutos)a.frutos=Math.min(a.capacidadeFrutos,a.frutos+Math.max(.1,a.saude/100*.6));else a.frutos=Math.max(0,a.frutos-.005);if(ev.regeneracaoVegetal)a.saude=Math.min(100,a.saude+.1);a.idade+=.002;if(a.idade>100)a.saude=Math.max(0,a.saude-.5);if(a.saude<=0&&!a.madeiraLiberada){x.madeira.floresta+=.5;a.madeiraLiberada=true}}const p=x.peixes.rio;if(ev.reproducaoPeixes&&p.populacao>0)p.populacao=Math.min(p.capacidade,p.populacao+Math.max(0,p.populacao*.035-.3));p.idadeMedia+=.002;if(p.idadeMedia>80&&m.tempo.ciclo%4===0)p.populacao=Math.max(0,p.populacao-.05);for(const a of Object.values(x.animais)){if(a.populacao<=0)continue;if(ev.frutificacao&&ev.regeneracaoVegetal)a.populacao=Math.min(a.capacidade,a.populacao+.04);a.idadeMedia+=.002;if(a.idadeMedia>80&&m.tempo.ciclo%4===0)a.populacao=Math.max(0,a.populacao-.02)}}
module.exports={VERSAO,novo,migrar,validar,avancar,regenerar,ESTACOES};
