'use strict';
const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path');
const schema=require('./estado-v2'),{novo,migrar,validar,avancar,regenerar}=schema,{acoes,executar,ciclo}=require('./motor-v2'),{gravar,carregar,anexar}=require('./persistencia-v2'),{perceber}=require('./percepcao-v2'),{executarCiclos}=require('./ilha');
let total=0;function t(nome,fn){return Promise.resolve().then(fn).then(()=>{total++;console.log('OK '+nome)})}
(async()=>{
await t('contrato V3 e fonte única do ciclo',()=>{const e=novo();validar(e);assert.equal(e.versao,3);assert(Number.isInteger(e.mundo.tempo.ciclo));assert(!('ciclos'in e.mundo.tempo));assert(!('ultimoCiclo'in e))});
await t('estado incompleto falha claramente',()=>assert.throws(()=>validar({versao:3}),/Estado V2 inválido/));
await t('migração V2 preserva recursos, necessidades e memórias e remove contador duplicado',()=>{const e=novo();e.versao=2;e.mundo.tempo.ciclos=e.mundo.tempo.ciclo;e.ultimoCiclo=1;e.seres.icaro.inventario.agua=3;e.memorias=[{texto:'memória anterior'}];const m=migrar(e);assert.equal(m.versao,3);assert.equal(m.seres.icaro.inventario.agua,3);assert.equal(m.memorias[0].texto,'memória anterior');assert(!('ciclos'in m.mundo.tempo))});
await t('migração ambígua é recusada sem descarte',()=>assert.throws(()=>migrar({versao:2,mundo:{ecossistema:{}},seres:{}}),/Migração V2 cancelada/));
await t('persistência conserva o estado lógico',()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'ilha-v3-')),f=path.join(d,'estado.json'),e=novo();e.memorias.push({texto:'auditável'});gravar(f,e);assert.deepStrictEqual(carregar(f),e);fs.rmSync(d,{recursive:true,force:true})});
await t('ação permitida aplica consequência calculada do estoque',()=>{const e=novo(),s=e.seres.icaro;s.local='rio';const antes=e.mundo.ecossistema.agua.nascente,r=executar(e,s,'coletar_agua');assert(r.quantidade>0);assert(e.mundo.ecossistema.agua.nascente<antes);assert(s.inventario.agua>8)});
await t('ação inválida não muda o estado',()=>{const e=novo(),antes=JSON.stringify(e);assert.throws(()=>executar(e,e.seres.icaro,'inventar_recurso'),/Ação inválida/);assert.equal(JSON.stringify(e),antes)});
await t('estoque zerado não oferece coleta e peixes zerados não renascem',()=>{const e=novo();e.seres.icaro.local='rio';e.mundo.ecossistema.agua.nascente=0;e.mundo.ecossistema.peixes.rio.populacao=0;assert(!acoes(e,e.seres.icaro).some(a=>a.id==='pescar'));const b=e.mundo.ecossistema.agua.nascente;regenerar(e.mundo,{chuva:'seco',frutificacao:false,reproducaoPeixes:true,regeneracaoVegetal:false});assert.equal(e.mundo.ecossistema.agua.nascente,b);assert.equal(e.mundo.ecossistema.peixes.rio.populacao,0)});
await t('calendário avança períodos e estações uma vez',()=>{const e=novo();e.mundo.tempo.ciclo=119;e.mundo.tempo=require('./calendario').tempoDe(119);const ev=avancar(e.mundo);assert.equal(e.mundo.tempo.ciclo,120);assert.equal(e.mundo.tempo.estacao,'transicao_umida');assert(ev.frutificacao)});
await t('regeneração respeita capacidades e requisitos sazonais',()=>{const e=novo(),m=e.mundo,b=m.ecossistema.agua.nascente;regenerar(m,{chuva:'chuva_forte',frutificacao:true,reproducaoPeixes:true,regeneracaoVegetal:true});assert(m.ecossistema.agua.nascente>b);assert(m.ecossistema.arvores.a.frutos<=m.ecossistema.arvores.a.capacidadeFrutos);assert(m.ecossistema.peixes.rio.populacao<=m.ecossistema.peixes.rio.capacidade)});
await t('percepção deriva do local e estoque sem revelar números',()=>{const e=novo();e.seres.icaro.local='rio';const p=perceber(e,e.seres.icaro).join(' ');assert(p.includes('rio')&&p.includes('Peixes'));assert(!/\b24\b|estoque/i.test(p))});
await t('observação separa pista percebida de descoberta e evento',()=>{const e=novo(),s=e.seres.icaro;s.local='rio';const p=perceber(e,s);assert(p.length);assert.equal(e.descobertas.length,0);const r=executar(e,s,'observar');assert.deepStrictEqual(r.pistas,p);assert.equal(e.descobertas.length,0)});
await t('estado biológico muda por necessidade real',()=>{const e=novo(),s=e.seres.icaro;s.necessidades.agua=70;require('./seres').atualizar(s,e.mundo,'esperar');assert.equal(s.status,'critico');s.necessidades.agua=100;require('./seres').atualizar(s,e.mundo,'esperar');assert.equal(s.status,'morto')});
await t('falha do decisor deixa ciclo sem avançar ou persistir',async()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'ilha-fail-')),e=novo(),f=path.join(d,'estado.json'),l=path.join(d,'log.jsonl');gravar(f,e);await assert.rejects(executarCiclos(1,{estado:e,arquivoEstado:f,arquivoLog:l,decisor:async()=>{throw Error('offline')}}),/Decisor indisponível/);assert.equal(carregar(f).mundo.tempo.ciclo,e.mundo.tempo.ciclo);assert(!fs.existsSync(l));fs.rmSync(d,{recursive:true,force:true})});
await t('ciclo integrado, interrupção, retomada e sem duplicação',async()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'ilha-resume-')),f=path.join(d,'estado.json'),l=path.join(d,'logs','ciclos.jsonl'),e=novo(),pick=async(c,a)=>({acao:a.some(x=>x.id==='observar')?'observar':a[0].id,motivo:'observar pista'});gravar(f,e);await executarCiclos(2,{estado:carregar(f),arquivoEstado:f,arquivoLog:l,decisor:pick});const retomado=carregar(f),c=retomado.mundo.tempo.ciclo;await executarCiclos(2,{estado:retomado,arquivoEstado:f,arquivoLog:l,decisor:pick});const final=carregar(f),linhas=fs.readFileSync(l,'utf8').trim().split('\n').map(JSON.parse);assert.equal(final.mundo.tempo.ciclo,c+2);assert.equal(linhas.length,4);assert.equal(new Set(linhas.map(x=>x.ciclo)).size,4);assert(!('estadoAntes'in linhas[0]));fs.rmSync(d,{recursive:true,force:true})});
console.log('RESULTADO '+total+' testes OK');
})().catch(e=>{console.error(e);process.exitCode=1});
