const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path');
const {novo,avancar,regenerar}=require('./mundo'),{acoes,executar}=require('./motor'),{interpretar,prompt}=require('./decisor'),{gravar,carregar,anexar}=require('./persistencia'),{perceber}=require('./percepcao');
let total=0;function t(nome,fn){fn();total++;console.log('OK '+nome)}
t('água coletada reduz a nascente e aumenta inventário',()=>{let e=novo(),s=e.seres.icaro;s.local='rio';let b=e.mundo.ecossistema.agua.nascente;executar(e,s,'coletar_agua');assert(s.inventario.agua>8&&e.mundo.ecossistema.agua.nascente<b)});
t('beber e comer consomem estoques carregados',()=>{let e=novo(),s=e.seres.icaro;executar(e,s,'beber');assert.equal(s.inventario.agua,7);executar(e,s,'comer');assert.equal(s.inventario.alimento,6)});
t('colheita reduz frutos existentes',()=>{let e=novo(),s=e.seres.icaro;s.local='bosque';let b=Object.values(e.mundo.ecossistema.arvores).reduce((n,a)=>n+a.frutos,0);executar(e,s,'colher_frutas');assert(Object.values(e.mundo.ecossistema.arvores).reduce((n,a)=>n+a.frutos,0)<b)});
t('calendário comprime períodos, dias, estações e anos',()=>{let m=novo().mundo;m.tempo.ciclos=119;let ev=avancar(m);assert.equal(m.tempo.estacao,'transicao_umida');assert(ev.frutificacao);for(let i=0;i<360;i++)avancar(m);assert(m.tempo.ano>=2)});
t('chuva regenera água; estação regenera frutos e peixes',()=>{let m=novo().mundo,b=m.ecossistema.agua.nascente,f=m.ecossistema.arvores.a.frutos,p=m.ecossistema.peixes.rio.populacao;regenerar(m,{chuva:'chuva_forte',frutificacao:true,reproducaoPeixes:true,regeneracaoVegetal:true});assert(m.ecossistema.agua.nascente>b&&m.ecossistema.arvores.a.frutos>f&&m.ecossistema.peixes.rio.populacao>p)});
t('recurso esgotado não permite pesca nem gera população espontânea',()=>{let e=novo();e.seres.icaro.local='rio';e.mundo.ecossistema.peixes.rio.populacao=0;assert(!acoes(e,e.seres.icaro).some(x=>x.id==='pescar'));regenerar(e.mundo,{chuva:'seco',frutificacao:false,reproducaoPeixes:false,regeneracaoVegetal:false});assert.equal(e.mundo.ecossistema.peixes.rio.populacao,0)});
t('consequência da pesca depende do estoque real',()=>{let a=novo(),b=novo();a.seres.icaro.local=b.seres.icaro.local='rio';a.mundo.tempo.ciclos=b.mundo.tempo.ciclos=0;a.mundo.tempo.ciclo=b.mundo.tempo.ciclo=0;a.mundo.ecossistema.peixes.rio.populacao=40;b.mundo.ecossistema.peixes.rio.populacao=1;assert.notEqual(executar(a,a.seres.icaro,'pescar').quantidade,executar(b,b.seres.icaro,'pescar').quantidade)});
t('modelo recebe situação e ações e a escolha valida origem permitida',()=>{let aa=[{id:'esperar'}];assert(prompt({necessidades:{agua:2}},aa)[1].content.includes('acoesPossiveis'));assert.equal(interpretar('{"acao":"esperar","motivo":"avaliar"}',aa).acao,'esperar');assert.throws(()=>interpretar('{"acao":"x","motivo":"x"}',aa))});
t('percepção revela pistas locais sem expor população numérica',()=>{let e=novo();e.seres.icaro.local='bosque';let p=perceber(e,e.seres.icaro).join(' ');assert(p.includes('frutíferas')&&!p.includes('24')&&!p.includes('estoque'))});
t('status biológico contempla crítico e morto',()=>{let e=novo(),s=e.seres.icaro;s.necessidades.agua=70;require('./seres').atualizar(s,e.mundo,'esperar');assert.equal(s.status,'critico');s.necessidades.agua=100;require('./seres').atualizar(s,e.mundo,'esperar');assert.equal(s.status,'morto')});
t('JSON completo e JSONL permitem retomar após reiniciar',()=>{let d=fs.mkdtempSync(path.join(os.tmpdir(),'ilha-v2-')),f=path.join(d,'estado.json'),l=path.join(d,'logs','ilha.jsonl'),e=novo();gravar(f,e);anexar(l,{tempo:e.mundo.tempo,decisao:{acao:'observar'},consequenciaReal:{quantidade:0}});let rec=carregar(f),linha=JSON.parse(fs.readFileSync(l,'utf8'));assert.equal(rec.mundo.tempo.ciclos,e.mundo.tempo.ciclos);assert.equal(linha.decisao.acao,'observar');fs.rmSync(d,{recursive:true,force:true})});
console.log('RESULTADO '+total+' testes OK');